/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */
package userinterface;

/**
 *
 * @author acer
 */
public class framePembelian extends javax.swing.JFrame {

    /**
     * Creates new form framePembelian
     */
    public framePembelian() {
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        viewHarga = new javax.swing.JLabel();
        jPanel1 = new javax.swing.JPanel();
        idKasir = new javax.swing.JLabel();
        inputIDKasir = new javax.swing.JTextField();
        idBarang = new javax.swing.JLabel();
        inputIDBarang = new javax.swing.JTextField();
        txtNamaBarang = new javax.swing.JTextField();
        inputQTY = new javax.swing.JTextField();
        txtHargaBarang = new javax.swing.JTextField();
        txtTotalHarga = new javax.swing.JTextField();
        jScrollPane1 = new javax.swing.JScrollPane();
        jTable1 = new javax.swing.JTable();
        totalHarga = new javax.swing.JLabel();
        txtJumlahHarga = new javax.swing.JTextField();
        diskon = new javax.swing.JLabel();
        txtDiskon = new javax.swing.JTextField();
        txtHasilDiskon = new javax.swing.JTextField();
        statusMember = new javax.swing.JLabel();
        member = new javax.swing.JRadioButton();
        nonMember = new javax.swing.JRadioButton();
        ppn = new javax.swing.JCheckBox();
        hasilPPN = new javax.swing.JTextField();
        hargaAkhir = new javax.swing.JLabel();
        hasilHargaAkhir = new javax.swing.JTextField();
        totalItem = new javax.swing.JLabel();
        hasilTotalItem = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        viewHarga.setFont(new java.awt.Font("Times New Roman", 1, 36)); // NOI18N
        viewHarga.setHorizontalAlignment(javax.swing.SwingConstants.RIGHT);
        viewHarga.setText("Rp. ");

        jPanel1.setBorder(javax.swing.BorderFactory.createEtchedBorder());

        idKasir.setFont(new java.awt.Font("Times New Roman", 0, 12)); // NOI18N
        idKasir.setText("ID Kasir");

        inputIDKasir.setFont(new java.awt.Font("Times New Roman", 0, 12)); // NOI18N
        inputIDKasir.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                inputIDKasirActionPerformed(evt);
            }
        });

        idBarang.setFont(new java.awt.Font("Times New Roman", 0, 12)); // NOI18N
        idBarang.setText("ID Barang");

        inputIDBarang.setFont(new java.awt.Font("Times New Roman", 0, 12)); // NOI18N

        txtNamaBarang.setFont(new java.awt.Font("Times New Roman", 0, 12)); // NOI18N

        inputQTY.setFont(new java.awt.Font("Times New Roman", 0, 12)); // NOI18N

        txtHargaBarang.setFont(new java.awt.Font("Times New Roman", 0, 12)); // NOI18N
        txtHargaBarang.setHorizontalAlignment(javax.swing.JTextField.RIGHT);

        txtTotalHarga.setFont(new java.awt.Font("Times New Roman", 0, 12)); // NOI18N
        txtTotalHarga.setHorizontalAlignment(javax.swing.JTextField.RIGHT);
        txtTotalHarga.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                txtTotalHargaActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout jPanel1Layout = new javax.swing.GroupLayout(jPanel1);
        jPanel1.setLayout(jPanel1Layout);
        jPanel1Layout.setHorizontalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addGap(16, 16, 16)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(idKasir)
                    .addComponent(idBarang, javax.swing.GroupLayout.PREFERRED_SIZE, 59, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addComponent(inputIDKasir)
                    .addComponent(inputIDBarang, javax.swing.GroupLayout.DEFAULT_SIZE, 250, Short.MAX_VALUE))
                .addGap(36, 36, 36)
                .addComponent(txtNamaBarang, javax.swing.GroupLayout.DEFAULT_SIZE, 253, Short.MAX_VALUE)
                .addGap(36, 36, 36)
                .addComponent(txtHargaBarang, javax.swing.GroupLayout.PREFERRED_SIZE, 250, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(36, 36, 36)
                .addComponent(inputQTY, javax.swing.GroupLayout.PREFERRED_SIZE, 42, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(36, 36, 36)
                .addComponent(txtTotalHarga, javax.swing.GroupLayout.PREFERRED_SIZE, 250, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(221, 221, 221))
        );
        jPanel1Layout.setVerticalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(idKasir)
                    .addComponent(inputIDKasir, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(idBarang)
                    .addComponent(inputIDBarang, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(txtNamaBarang, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(txtHargaBarang, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(inputQTY, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(txtTotalHarga, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addContainerGap(16, Short.MAX_VALUE))
        );

        jTable1.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {null, null, null, null, null, null, null},
                {null, null, null, null, null, null, null},
                {null, null, null, null, null, null, null},
                {null, null, null, null, null, null, null}
            },
            new String [] {
                "No", "ID Barang", "Nama Barang", "Jumlah Barang", "Harga Barang", "Diskon", "Total Harga"
            }
        ));
        jScrollPane1.setViewportView(jTable1);

        totalHarga.setFont(new java.awt.Font("Times New Roman", 1, 12)); // NOI18N
        totalHarga.setText("JUMLAH HARGA");

        txtJumlahHarga.setFont(new java.awt.Font("Times New Roman", 0, 12)); // NOI18N

        diskon.setFont(new java.awt.Font("Times New Roman", 1, 12)); // NOI18N
        diskon.setText("DISKON");

        txtDiskon.setFont(new java.awt.Font("Times New Roman", 0, 12)); // NOI18N

        txtHasilDiskon.setFont(new java.awt.Font("Times New Roman", 0, 12)); // NOI18N

        statusMember.setFont(new java.awt.Font("Times New Roman", 1, 12)); // NOI18N
        statusMember.setText("STATUS MEMBER");

        member.setFont(new java.awt.Font("Times New Roman", 0, 12)); // NOI18N
        member.setText("Member");

        nonMember.setFont(new java.awt.Font("Times New Roman", 0, 12)); // NOI18N
        nonMember.setText("Non Member");

        ppn.setFont(new java.awt.Font("Times New Roman", 1, 12)); // NOI18N
        ppn.setText("PPN 6%");

        hasilPPN.setFont(new java.awt.Font("Times New Roman", 0, 12)); // NOI18N

        hargaAkhir.setFont(new java.awt.Font("Times New Roman", 1, 12)); // NOI18N
        hargaAkhir.setText("HARGA AKHIR");

        hasilHargaAkhir.setFont(new java.awt.Font("Times New Roman", 0, 12)); // NOI18N

        totalItem.setFont(new java.awt.Font("Times New Roman", 1, 12)); // NOI18N
        totalItem.setText("TOTAL ITEM ");

        hasilTotalItem.setFont(new java.awt.Font("Times New Roman", 1, 12)); // NOI18N
        hasilTotalItem.setText("0");

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jScrollPane1)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                        .addComponent(totalItem)
                        .addGap(18, 18, 18)
                        .addComponent(hasilTotalItem, javax.swing.GroupLayout.PREFERRED_SIZE, 30, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                                    .addComponent(diskon)
                                    .addGap(118, 118, 118))
                                .addGroup(layout.createSequentialGroup()
                                    .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                        .addComponent(statusMember)
                                        .addComponent(totalHarga))
                                    .addGap(62, 62, 62)))
                            .addGroup(layout.createSequentialGroup()
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addComponent(ppn, javax.swing.GroupLayout.PREFERRED_SIZE, 85, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addComponent(hargaAkhir))
                                .addGap(80, 80, 80)))
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(hasilPPN, javax.swing.GroupLayout.PREFERRED_SIZE, 250, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addGroup(layout.createSequentialGroup()
                                .addComponent(member)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addComponent(nonMember))
                            .addGroup(layout.createSequentialGroup()
                                .addComponent(txtDiskon, javax.swing.GroupLayout.PREFERRED_SIZE, 42, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addComponent(txtHasilDiskon, javax.swing.GroupLayout.PREFERRED_SIZE, 202, javax.swing.GroupLayout.PREFERRED_SIZE))
                            .addComponent(txtJumlahHarga, javax.swing.GroupLayout.PREFERRED_SIZE, 250, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(hasilHargaAkhir, javax.swing.GroupLayout.PREFERRED_SIZE, 250, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addGap(132, 132, 132))
                    .addGroup(layout.createSequentialGroup()
                        .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addContainerGap())
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                        .addGap(0, 0, Short.MAX_VALUE)
                        .addComponent(viewHarga, javax.swing.GroupLayout.PREFERRED_SIZE, 339, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(89, 89, 89))))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(43, 43, 43)
                .addComponent(viewHarga)
                .addGap(34, 34, 34)
                .addComponent(jPanel1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 270, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(18, 18, 18)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(totalHarga)
                    .addComponent(txtJumlahHarga, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(totalItem)
                    .addComponent(hasilTotalItem))
                .addGap(8, 8, 8)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(statusMember)
                    .addComponent(member)
                    .addComponent(nonMember))
                .addGap(8, 8, 8)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(diskon)
                    .addComponent(txtDiskon, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(txtHasilDiskon, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(ppn)
                    .addComponent(hasilPPN, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(hargaAkhir)
                    .addComponent(hasilHargaAkhir, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addContainerGap(99, Short.MAX_VALUE))
        );

        setSize(new java.awt.Dimension(1533, 738));
        setLocationRelativeTo(null);
    }// </editor-fold>//GEN-END:initComponents

    private void inputIDKasirActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_inputIDKasirActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_inputIDKasirActionPerformed

    private void txtTotalHargaActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_txtTotalHargaActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_txtTotalHargaActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(framePembelian.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(framePembelian.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(framePembelian.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(framePembelian.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new framePembelian().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JLabel diskon;
    private javax.swing.JLabel hargaAkhir;
    private javax.swing.JTextField hasilHargaAkhir;
    private javax.swing.JTextField hasilPPN;
    private javax.swing.JLabel hasilTotalItem;
    private javax.swing.JLabel idBarang;
    private javax.swing.JLabel idKasir;
    private javax.swing.JTextField inputIDBarang;
    private javax.swing.JTextField inputIDKasir;
    private javax.swing.JTextField inputQTY;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JTable jTable1;
    private javax.swing.JRadioButton member;
    private javax.swing.JRadioButton nonMember;
    private javax.swing.JCheckBox ppn;
    private javax.swing.JLabel statusMember;
    private javax.swing.JLabel totalHarga;
    private javax.swing.JLabel totalItem;
    private javax.swing.JTextField txtDiskon;
    private javax.swing.JTextField txtHargaBarang;
    private javax.swing.JTextField txtHasilDiskon;
    private javax.swing.JTextField txtJumlahHarga;
    private javax.swing.JTextField txtNamaBarang;
    private javax.swing.JTextField txtTotalHarga;
    private javax.swing.JLabel viewHarga;
    // End of variables declaration//GEN-END:variables
}
