/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */
package userinterface;

/**
 *
 * @author user
 */
public class framePembelian extends javax.swing.JFrame {

    /**
     * Creates new form framePembelian
     */
    public framePembelian() {
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanel1 = new javax.swing.JPanel();
        labelIdPembelian = new javax.swing.JLabel();
        inputIdBarang = new javax.swing.JTextField();
        inputIdAdmin = new javax.swing.JTextField();
        btnCariBarang = new javax.swing.JButton();
        btnCariAdmin = new javax.swing.JButton();
        labelNamaAdmin = new javax.swing.JLabel();
        inputDistributor = new javax.swing.JTextField();
        labelNamaBarang = new javax.swing.JLabel();
        inputJumlah = new javax.swing.JTextField();
        inputIsiPerBox = new javax.swing.JTextField();
        inputHargaPerBox = new javax.swing.JTextField();
        labelRP = new javax.swing.JLabel();
        labelTotalHarga = new javax.swing.JLabel();
        btnHapus = new javax.swing.JButton();
        btnTambah = new javax.swing.JButton();
        btnUbah = new javax.swing.JButton();
        jScrollPane1 = new javax.swing.JScrollPane();
        jTable1 = new javax.swing.JTable();
        bg = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        getContentPane().setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jPanel1.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        labelIdPembelian.setForeground(new java.awt.Color(0, 0, 0));
        labelIdPembelian.setText("jLabel1");
        jPanel1.add(labelIdPembelian, new org.netbeans.lib.awtextra.AbsoluteConstraints(50, 150, -1, -1));

        inputIdBarang.setText("jTextField1");
        jPanel1.add(inputIdBarang, new org.netbeans.lib.awtextra.AbsoluteConstraints(30, 440, 270, 40));

        inputIdAdmin.setText("jTextField1");
        jPanel1.add(inputIdAdmin, new org.netbeans.lib.awtextra.AbsoluteConstraints(30, 260, 270, 40));

        btnCariBarang.setForeground(new java.awt.Color(0, 0, 0));
        btnCariBarang.setText("Cari");
        jPanel1.add(btnCariBarang, new org.netbeans.lib.awtextra.AbsoluteConstraints(300, 440, 110, 40));

        btnCariAdmin.setForeground(new java.awt.Color(0, 0, 0));
        btnCariAdmin.setText("Cari");
        jPanel1.add(btnCariAdmin, new org.netbeans.lib.awtextra.AbsoluteConstraints(300, 260, 110, 40));

        labelNamaAdmin.setForeground(new java.awt.Color(0, 0, 0));
        labelNamaAdmin.setText("jLabel1");
        jPanel1.add(labelNamaAdmin, new org.netbeans.lib.awtextra.AbsoluteConstraints(40, 326, 360, 30));

        inputDistributor.setText("jTextField1");
        jPanel1.add(inputDistributor, new org.netbeans.lib.awtextra.AbsoluteConstraints(30, 380, 380, 40));

        labelNamaBarang.setText("jLabel1");
        jPanel1.add(labelNamaBarang, new org.netbeans.lib.awtextra.AbsoluteConstraints(40, 500, 370, 40));

        inputJumlah.setText("jTextField1");
        jPanel1.add(inputJumlah, new org.netbeans.lib.awtextra.AbsoluteConstraints(32, 560, 170, 40));

        inputIsiPerBox.setText("jTextField1");
        jPanel1.add(inputIsiPerBox, new org.netbeans.lib.awtextra.AbsoluteConstraints(230, 560, 180, 40));

        inputHargaPerBox.setText("jTextField1");
        jPanel1.add(inputHargaPerBox, new org.netbeans.lib.awtextra.AbsoluteConstraints(30, 620, 380, 40));

        labelRP.setFont(new java.awt.Font("Arial Rounded MT Bold", 1, 36)); // NOI18N
        labelRP.setForeground(new java.awt.Color(0, 0, 0));
        labelRP.setText("Rp");
        jPanel1.add(labelRP, new org.netbeans.lib.awtextra.AbsoluteConstraints(160, 660, -1, 50));

        labelTotalHarga.setFont(new java.awt.Font("Arial Rounded MT Bold", 1, 36)); // NOI18N
        labelTotalHarga.setForeground(new java.awt.Color(0, 0, 0));
        labelTotalHarga.setText("200000");
        jPanel1.add(labelTotalHarga, new org.netbeans.lib.awtextra.AbsoluteConstraints(220, 660, 190, 50));

        btnHapus.setText("Hapus");
        jPanel1.add(btnHapus, new org.netbeans.lib.awtextra.AbsoluteConstraints(490, 290, 120, 60));

        btnTambah.setText("Tambah");
        btnTambah.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnTambahActionPerformed(evt);
            }
        });
        jPanel1.add(btnTambah, new org.netbeans.lib.awtextra.AbsoluteConstraints(490, 150, 120, 60));

        btnUbah.setText("Ubah");
        jPanel1.add(btnUbah, new org.netbeans.lib.awtextra.AbsoluteConstraints(490, 220, 120, 60));

        jTable1.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {null, null, null, null, null, null, null, null, null, null, null},
                {null, null, null, null, null, null, null, null, null, null, null},
                {null, null, null, null, null, null, null, null, null, null, null},
                {null, null, null, null, null, null, null, null, null, null, null}
            },
            new String [] {
                "Id Pembelian", "Tgl", "Id Admin", "Nama Admin", "Distributor", "Id Barang", "Barang", "Jumlah(box)", "Isi /box", "Harga /box", "Total Harga"
            }
        ) {
            boolean[] canEdit = new boolean [] {
                false, false, false, false, false, false, false, false, false, false, false
            };

            public boolean isCellEditable(int rowIndex, int columnIndex) {
                return canEdit [columnIndex];
            }
        });
        jScrollPane1.setViewportView(jTable1);

        jPanel1.add(jScrollPane1, new org.netbeans.lib.awtextra.AbsoluteConstraints(626, 110, 680, 630));

        bg.setIcon(new javax.swing.ImageIcon(getClass().getResource("/background/pagePembelian.png"))); // NOI18N
        jPanel1.add(bg, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, -1, -1));

        getContentPane().add(jPanel1, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, 1300, 730));

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void btnTambahActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnTambahActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_btnTambahActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(framePembelian.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(framePembelian.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(framePembelian.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(framePembelian.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new framePembelian().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JLabel bg;
    private javax.swing.JButton btnCariAdmin;
    private javax.swing.JButton btnCariBarang;
    private javax.swing.JButton btnHapus;
    private javax.swing.JButton btnTambah;
    private javax.swing.JButton btnUbah;
    private javax.swing.JTextField inputDistributor;
    private javax.swing.JTextField inputHargaPerBox;
    private javax.swing.JTextField inputIdAdmin;
    private javax.swing.JTextField inputIdBarang;
    private javax.swing.JTextField inputIsiPerBox;
    private javax.swing.JTextField inputJumlah;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JTable jTable1;
    private javax.swing.JLabel labelIdPembelian;
    private javax.swing.JLabel labelNamaAdmin;
    private javax.swing.JLabel labelNamaBarang;
    private javax.swing.JLabel labelRP;
    private javax.swing.JLabel labelTotalHarga;
    // End of variables declaration//GEN-END:variables
}
