/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */
package userinterface;

/**
 *
 * @author Asus
 */
public class frameDataMember extends javax.swing.JFrame {

    /**
     * Creates new form frameDataMember
     */
    public frameDataMember() {
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        inputAlamatMember = new javax.swing.JTextField();
        inputEmailMember = new javax.swing.JTextField();
        inputNomorHpMember = new javax.swing.JTextField();
        inputNamaMember = new javax.swing.JTextField();
        inputIDMember = new javax.swing.JTextField();
        btnHapus = new javax.swing.JButton();
        btnUbah = new javax.swing.JButton();
        btnTambah = new javax.swing.JButton();
        btnBack = new javax.swing.JButton();
        jScrollPane1 = new javax.swing.JScrollPane();
        tabelDataMember = new javax.swing.JTable();
        bgDataMember = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        getContentPane().setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        inputAlamatMember.setFont(new java.awt.Font("Segoe UI", 0, 14)); // NOI18N
        inputAlamatMember.setBorder(null);
        inputAlamatMember.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                inputAlamatMemberActionPerformed(evt);
            }
        });
        getContentPane().add(inputAlamatMember, new org.netbeans.lib.awtextra.AbsoluteConstraints(40, 480, 400, 30));

        inputEmailMember.setFont(new java.awt.Font("Segoe UI", 0, 14)); // NOI18N
        inputEmailMember.setBorder(null);
        inputEmailMember.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                inputEmailMemberActionPerformed(evt);
            }
        });
        getContentPane().add(inputEmailMember, new org.netbeans.lib.awtextra.AbsoluteConstraints(40, 400, 400, 30));

        inputNomorHpMember.setFont(new java.awt.Font("Segoe UI", 0, 14)); // NOI18N
        inputNomorHpMember.setBorder(null);
        inputNomorHpMember.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                inputNomorHpMemberActionPerformed(evt);
            }
        });
        getContentPane().add(inputNomorHpMember, new org.netbeans.lib.awtextra.AbsoluteConstraints(40, 320, 400, 30));

        inputNamaMember.setFont(new java.awt.Font("Segoe UI", 0, 14)); // NOI18N
        inputNamaMember.setBorder(null);
        inputNamaMember.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                inputNamaMemberActionPerformed(evt);
            }
        });
        getContentPane().add(inputNamaMember, new org.netbeans.lib.awtextra.AbsoluteConstraints(40, 240, 400, 30));

        inputIDMember.setFont(new java.awt.Font("Segoe UI", 0, 14)); // NOI18N
        inputIDMember.setBorder(null);
        inputIDMember.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                inputIDMemberActionPerformed(evt);
            }
        });
        getContentPane().add(inputIDMember, new org.netbeans.lib.awtextra.AbsoluteConstraints(40, 160, 400, 30));

        btnHapus.setBackground(java.awt.Color.lightGray);
        btnHapus.setFont(new java.awt.Font("Segoe UI", 1, 14)); // NOI18N
        btnHapus.setText("Hapus");
        getContentPane().add(btnHapus, new org.netbeans.lib.awtextra.AbsoluteConstraints(500, 310, 110, 70));

        btnUbah.setBackground(java.awt.Color.lightGray);
        btnUbah.setFont(new java.awt.Font("Segoe UI", 1, 14)); // NOI18N
        btnUbah.setText("Ubah");
        btnUbah.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnUbahActionPerformed(evt);
            }
        });
        getContentPane().add(btnUbah, new org.netbeans.lib.awtextra.AbsoluteConstraints(500, 170, 110, 70));

        btnTambah.setBackground(java.awt.Color.lightGray);
        btnTambah.setFont(new java.awt.Font("Segoe UI", 1, 14)); // NOI18N
        btnTambah.setText("Tambah");
        getContentPane().add(btnTambah, new org.netbeans.lib.awtextra.AbsoluteConstraints(500, 240, 110, 70));

        btnBack.setBackground(java.awt.Color.gray);
        btnBack.setFont(new java.awt.Font("Century Gothic", 1, 18)); // NOI18N
        btnBack.setForeground(new java.awt.Color(255, 255, 255));
        btnBack.setIcon(new javax.swing.ImageIcon(getClass().getResource("/background/homebutton.png"))); // NOI18N
        btnBack.setText("BACK");
        btnBack.setBorder(null);
        btnBack.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnBackActionPerformed(evt);
            }
        });
        getContentPane().add(btnBack, new org.netbeans.lib.awtextra.AbsoluteConstraints(1120, 30, 120, 40));

        tabelDataMember.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {null, null, null, null, null},
                {null, null, null, null, null},
                {null, null, null, null, null},
                {null, null, null, null, null}
            },
            new String [] {
                "ID Member", "Nama Member", "Nomor HP", "Email", "Alamat "
            }
        ) {
            Class[] types = new Class [] {
                java.lang.String.class, java.lang.String.class, java.lang.Integer.class, java.lang.String.class, java.lang.String.class
            };

            public Class getColumnClass(int columnIndex) {
                return types [columnIndex];
            }
        });
        jScrollPane1.setViewportView(tabelDataMember);

        getContentPane().add(jScrollPane1, new org.netbeans.lib.awtextra.AbsoluteConstraints(640, 110, 670, 630));

        bgDataMember.setIcon(new javax.swing.ImageIcon(getClass().getResource("/background/pageDataMember.png"))); // NOI18N
        bgDataMember.setText("jLabel1");
        getContentPane().add(bgDataMember, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, 1300, -1));

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void inputIDMemberActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_inputIDMemberActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_inputIDMemberActionPerformed

    private void inputNamaMemberActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_inputNamaMemberActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_inputNamaMemberActionPerformed

    private void inputNomorHpMemberActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_inputNomorHpMemberActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_inputNomorHpMemberActionPerformed

    private void inputEmailMemberActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_inputEmailMemberActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_inputEmailMemberActionPerformed

    private void inputAlamatMemberActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_inputAlamatMemberActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_inputAlamatMemberActionPerformed

    private void btnUbahActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnUbahActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_btnUbahActionPerformed

    private void btnBackActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnBackActionPerformed
        // TODO add your handling code here:
        FrameLanding landing = new FrameLanding();
        landing.setVisible(true);
        this.dispose();
    }//GEN-LAST:event_btnBackActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(frameDataMember.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(frameDataMember.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(frameDataMember.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(frameDataMember.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new frameDataMember().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JLabel bgDataMember;
    private javax.swing.JButton btnBack;
    private javax.swing.JButton btnHapus;
    private javax.swing.JButton btnTambah;
    private javax.swing.JButton btnUbah;
    private javax.swing.JTextField inputAlamatMember;
    private javax.swing.JTextField inputEmailMember;
    private javax.swing.JTextField inputIDMember;
    private javax.swing.JTextField inputNamaMember;
    private javax.swing.JTextField inputNomorHpMember;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JTable tabelDataMember;
    // End of variables declaration//GEN-END:variables
}
